services:
  - type: web
    name: secret-gift-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
